{{ if .Values.base.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-basedeployment"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.base.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}-selector"
        version: "base"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.base.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ if .Values.istio.enabled }}
{{ else }}
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 120
          periodSeconds: 15
{{  end }}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: PORT
            value: "{{ .Values.service.servicePort }}"
          - name: USERNAME
            value: admin
          - name: PASSWORD
            value: password
          - name: MB_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-keystore-password
                key: password
          - name: MB_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-truststore-password
                key: password
        volumeMounts:
          - name: keystores
            mountPath: /etc/wlp/config/keystore
            readOnly: true
          - name: truststores
            mountPath: /etc/wlp/config/truststore
            readOnly: true
          - name: liberty-config
            mountPath: /config/configDropins
      volumes:
        - name: keystores
          secret:
            secretName: mb-keystore
        - name: truststores
          secret:
            secretName: mb-truststore
        - name: liberty-config
          configMap:
            name: liberty-logging-config
            items:
              - key: keystore.xml
                path: defaults/keystore.xml
              - key: logging.xml
                path: defaults/logging.xml
{{ end }}
